version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: taskdb
    environment:
      POSTGRES_DB: taskdb
      POSTGRES_PASSWORD: postgres
      POSTGRES_USERNAME: postgres
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: